foobox/Models/InvitationViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FooBox.Models
{

    public class EditInvitationsViewModel
    {
        public EditInvitationsViewModel()
        {
            FolderInvitations = new List<InvitationVM>();
            UsersToInvite = new List<EntitySelectedViewModel>();
            GroupsToInvite = new List<EntitySelectedViewModel>();
        }

        public string FullName { get; set; }

        public string FromPath { get; set; }

        public List<InvitationVM> FolderInvitations { get; set; }

        [DisplayName("Users")]
        public List<EntitySelectedViewModel> UsersToInvite { get; set; }

        [DisplayName("Group")]
        public List<EntitySelectedViewModel> GroupsToInvite { get; set; }

    }

    public enum InvitationDisallowedReason
    {
        None,
        NotOwner,
        InSharedFolder
    }


    public class AllInvitationsViewModel
    {
        public AllInvitationsViewModel()
        {

            Incoming = new List<InvitationVM>();
            Outgoing = new List<InvitationVM>();
        }

        public List<InvitationVM> Incoming { get; set; }
        public List<InvitationVM> Outgoing { get; set; }
    }


    public class InvitationVM
    {
        public string FolderName { get; set; }
        public long Id { get; set; }

        public string UserName { get; set; }

        public string GroupName { get; set; }

        public bool Accepted { get; set; }

        public DateTime Timestamp { get; set; }

    }



}

foobox/Controllers/InvitationController.cs
using FooBox.Common;
using FooBox.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FooBox.Controllers
{
    [Authorize]
    public class InvitationController : Controller
    {
        private FileManager _fileManager;
        private UserManager _userManager;

        public InvitationController()
        {
            _fileManager = new FileManager();
            _userManager = new UserManager(_fileManager.Context);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _fileManager.Dispose();
            }
            base.Dispose(disposing);
        }

        private InvitationDisallowedReason DetermineDisallowedReason(Folder folder)
        {
            long userId = User.Identity.GetUserId();

            if (folder.OwnerId != userId)
                return InvitationDisallowedReason.NotOwner;

            if (folder.InvitationId != null)
                return InvitationDisallowedReason.InSharedFolder;

            return InvitationDisallowedReason.None;
        }

        public ActionResult Index(string fullName)
        {
            if (fullName == null)
                return RedirectToAction("Browse", "File", null);

            Folder userRootFolder = _fileManager.GetUserRootFolder(User.Identity.GetUserId());
            User currentUser = _userManager.FindUser(User.Identity.GetUserId());
            string fullDisplayName;
            File file = _fileManager.FindFile(fullName, userRootFolder, out fullDisplayName);

            if (file == null || file is Document)
            {
                return HttpNotFound();
            }

            Folder folder = (Folder)file;

            if (DetermineDisallowedReason(folder) != InvitationDisallowedReason.None)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);

            var mod = new EditInvitationsViewModel();
            
            mod.FullName = fullName;
            mod.FromPath = _fileManager.GetFullDisplayName(file.ParentFolder, userRootFolder);
            
            var invitations = _fileManager.Context.Invitations.ToList();
            foreach (Invitation i in invitations)
            {
                if (i.TargetId == folder.Id)
                {
                    var ivm = new InvitationVM
                    {
                        Id = i.Id,
                        UserName = i.User.Name,
                        Timestamp = i.TimeStamp,
                        Accepted = i.AcceptedFolders.Any()
                    };
                    mod.FolderInvitations.Add(ivm);
                }
            }

            var uninvited = uninvitedUsers(fullName);
            foreach (User u in uninvited)
            {
                if (u == _userManager.GetDefaultUser() || 
                    u.State == ObjectState.Deleted || 
                    u == currentUser) continue;
                var e = new EntitySelectedViewModel
                {
                    Id = u.Id,
                    IsSelected = false,
                    Name = u.Name
                };
                mod.UsersToInvite.Add(e);
            }

            foreach (Group g in _userManager.Context.Groups)
            {
                if (g.State == ObjectState.Deleted) continue;
                var e = new EntitySelectedViewModel
                {
                    Id = g.Id,
                    IsSelected = false,
                    Name = g.Name
                };
                mod.GroupsToInvite.Add(e);
            }

            ViewBag.Subheading = folder.DisplayName;
            return View(mod);
        }

        public ActionResult AllInvitations()
        {
            long currentUserId = User.Identity.GetUserId();
            AllInvitationsViewModel mod = new AllInvitationsViewModel();

            mod.Incoming = (
                from i in _fileManager.Context.Invitations
                where i.UserId == currentUserId
                let accepted = i.AcceptedFolders.Any()
                orderby accepted ascending, i.TimeStamp descending
                select new InvitationVM
                {
                    Id = i.Id,
                    FolderName = i.Target.DisplayName,
                    UserName = i.Target.Owner.Name,
                    Timestamp = i.TimeStamp,
                    Accepted = accepted
                }
                ).ToList();
            mod.Outgoing = (
                from i in _fileManager.Context.Invitations
                where i.Target.OwnerId == currentUserId
                let accepted = i.AcceptedFolders.Any()
                orderby accepted ascending, i.TimeStamp descending
                select new InvitationVM
                {
                    Id = i.Id,
                    FolderName = i.Target.DisplayName,
                    UserName = i.User.Name,
                    Timestamp = i.TimeStamp,
                    Accepted = i.AcceptedFolders.Any()
                }
                ).ToList();

            return View(mod);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewInvitation(EditInvitationsViewModel model)
        {
            List<User> uninvited = new List<User>(uninvitedUsers(model.FullName));
            if (ModelState.IsValid)
            {
                Folder userRootFolder = _fileManager.GetUserRootFolder(User.Identity.GetUserId());
                User currentUser = _userManager.FindUser(User.Identity.GetUserId());
                string fullDisplayName;
                Folder f = (Folder)_fileManager.FindFile(model.FullName, userRootFolder, out fullDisplayName);

                if (DetermineDisallowedReason(f) != InvitationDisallowedReason.None)
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);

                foreach (var item in model.UsersToInvite)
                {
                    if (item.IsSelected)
                    {
                        FooBox.User u = _userManager.FindUser(item.Id);
                        var invitation = new Invitation
                        {
                            Target = f,
                            TargetId = f.Id,
                            User = u,
                            UserId = u.Id,
                            TimeStamp = DateTime.UtcNow
                        };
                        _userManager.Context.Invitations.Add(invitation);
                        _userManager.Context.SaveChanges();
                    } 
                }
                foreach (var item in model.GroupsToInvite)
                {
                    if (item.IsSelected)
                    {
                        FooBox.Group g = _userManager.FindGroup(item.Id);
                        foreach (User u in g.Users)
                        {
                            if (u == _userManager.GetDefaultUser() || 
                                u.State == ObjectState.Deleted ||
                                u == currentUser) continue;
                            if (uninvited.Contains(u))
                            {
                                uninvited.Remove(u);
                                var invitation = new Invitation
                                {
                                    Target = f,
                                    TargetId = f.Id,
                                    User = u,
                                    UserId = u.Id,
                                    TimeStamp = DateTime.UtcNow
                                }; 
                                _userManager.Context.Invitations.Add(invitation);
                                _userManager.Context.SaveChanges();
                            }
                        }
                    }
                }
                return RedirectToAction("Index", new { fullName = model.FullName });
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteInvitation(EditInvitationsViewModel model, long? id)
        {
            var inv = _fileManager.FindInvitation(id.Value);
            if (inv == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            DeleteInvitation(inv);
            return RedirectToAction("Index", new { fullName = model.FullName });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteInvitation2(long? id)
        {
            var inv = _fileManager.FindInvitation(id.Value);
            DeleteInvitation(inv);
            return RedirectToAction("AllInvitations");
        }

        private bool DeleteInvitation(Invitation invitation)
        {
            // Delete any associated accepted folder.

            var acceptedFolder = invitation.AcceptedFolders.SingleOrDefault();

            if (acceptedFolder != null)
            {
                var internalClient = _fileManager.GetInternalClient(acceptedFolder.OwnerId);
                ClientSyncData data = new ClientSyncData();

                data.ClientId = internalClient.Id;
                data.BaseChangelistId = _fileManager.GetLastChangelistId();
                data.Changes.Add(new ClientChange
                {
                    FullName = _fileManager.GetFullName(acceptedFolder),
                    Type = ChangeType.Delete
                });

                if (_fileManager.SyncClientChanges(data).State != ClientSyncResultState.Success)
                    return false;
            }

            // Delete the invitation.

            _fileManager.Context.Invitations.Remove(invitation);
            _fileManager.Context.SaveChanges();

            return true;
        }

        [HttpPost]
        // Returns new folder name
        public ActionResult EditStatus(long id, string submit)

foobox/Views/Invitation/Index.cshtml
@model FooBox.Models.EditInvitationsViewModel

@{
    ViewBag.Title = "Invitations";
}


<h2>@ViewBag.Subheading</h2>
<h4>Invitations</h4>



<p>
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Invite <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a id="inviteUsers" href="#">Users</a></li>
            <li><a id="inviteGroup" href="#">Groups</a></li>
        </ul>
    </div>
</p>
<table class="table table-hover">
    <tr>
        <th>
            User
        </th>
        <th>
            Date Invited
        </th>
        <th>
            Accepted
        </th>
        <th>

        </th>
    </tr>

    @for (int i = 0; i < Model.FolderInvitations.Count(); ++i)
    {
        var item = Model.FolderInvitations[i];
        <tr>
            <td class="col-md-2">
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td class="col-md-3">
                @Html.Encode(item.Timestamp.ToLocalTime().ToString("F"))
            </td>
            <td class="col-md-1">
                @if (item.Accepted)
                {
                    <span class="label label-success">Accepted</span>
                }
                else
                {
                    <span class="label label-default">Pending</span>
                }
            </td>
            <td id="@("inv" + @i)" class="col-md-1">
                <a href="#" class="deleteLink">Delete</a>
                <!-- Confirm Delete -->
                <div class="confirmDeleteDialog" id="@("confirminv" + @i)" style="display:none;">
                    @using (@Html.BeginForm("DeleteInvitation", "Invitation", new { id = item.Id }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.FullName)
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        <button type="button" class="delCancelButton btn btn-sm btn-default">Cancel</button>
                    }
                </div>

            </td>
        </tr>
    }
    @if (!Model.FolderInvitations.Any())
    {
        <tr>
            <td>
                <em>No invitations to display.</em>
            </td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to List", "Browse", "File", new { path = Model.FromPath }, null)
</div>

<div class="modal fade" id="usersModal">
    <div class="modal-dialog">
        <div class="modal-content">
        @using (@Html.BeginForm("NewInvitation", "Invitation", FormMethod.Post, new { @class = "form-horizontal", role = "form" })) 
        {
            @Html.AntiForgeryToken()
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Invite Users</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.UsersToInvite, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @for (int i = 0; i < Model.UsersToInvite.Count(); ++i)
                        {
                            @Html.HiddenFor(model => model.UsersToInvite[i].Id)
                            @Html.CheckBoxFor(model => model.UsersToInvite[i].IsSelected)
                            @Html.DisplayFor(model => model.UsersToInvite[i].Name)
                            @Html.HiddenFor(model => model.UsersToInvite[i].Name)
                            <br>
                        }
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success">Invite</button>
            </div>
            @Html.HiddenFor(model => model.FullName)
        }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<div class="modal fade" id="groupModal">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (@Html.BeginForm("NewInvitation", "Invitation", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Invite Groups</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.GroupsToInvite, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @for (int i = 0; i < Model.GroupsToInvite.Count(); ++i)
                            {
                                @Html.HiddenFor(model => model.GroupsToInvite[i].Id)
                                @Html.CheckBoxFor(model => model.GroupsToInvite[i].IsSelected)
                                @Html.DisplayFor(model => model.GroupsToInvite[i].Name)
                                @Html.HiddenFor(model => model.GroupsToInvite[i].Name)
                                <br>
                            }
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Invite</button>
                </div>
                @Html.HiddenFor(model => model.FullName)
            }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
    $("document").ready(function () {
        $("#inviteUsers").click(function () {
            $('#usersModal').modal("show");
        });
        $("#inviteGroup").click(function () {
            $('#groupModal').modal("show");
        });
        $(".deleteLink").click(function () {
            $(this).hide();
            var it = $(this).closest('td').attr('id');
            $("#confirm" + it).show('slide');
        });
        $(".delCancelButton").click(function () {
            $(".confirmDeleteDialog").hide();
            $(".deleteLink").show('slide');
        });
    });
</script>