FooBox/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;
using FooBox;
using FooBox.Models;
using System.Text;
using System.IO;
using System.Xml.Serialization;
using FooBox.Common;
using System.Data.Entity.Infrastructure;

namespace FooBox.Controllers
{
    [Authorize]
    public class FileController : Controller
    {
        private FileManager _fileManager;
        private UserManager _userManager;

        public FileController()
        {
            _fileManager = new FileManager();
            _userManager = new UserManager(_fileManager.Context);
        }

        public ActionResult Index()
        {
            return RedirectToAction("Browse");
        }

        private FileBrowseViewModel CreateBrowseModelForFolder(Folder folder, string fullDisplayName)
        {
            long userId = User.Identity.GetUserId();
            Folder userRootFolder = _fileManager.GetUserRootFolder(userId);

            if (folder == null)
            {
                folder = userRootFolder;
                fullDisplayName = "";
            }

            Folder originalFolder = folder;

            // Follow any invitation link.
            if (folder.InvitationId != null)
                folder = folder.Invitation.Target;

            FileBrowseViewModel model = new FileBrowseViewModel();

            model.FullDisplayName = fullDisplayName;
            model.DisplayName = originalFolder == userRootFolder ? "Home" : originalFolder.DisplayName;
            model.State = originalFolder.State;
            model.Files = (
                from file in folder.Files.AsQueryable()
                where file.State == ObjectState.Normal || file.State == folder.State // Always show deleted files in a deleted folder
                orderby !(file is Folder) ascending, file.Name ascending
                let latestVersion = (file is Document) ? (from version in ((Document)file).DocumentVersions.AsQueryable()
                                                          orderby version.TimeStamp descending
                                                          select version).FirstOrDefault()
                                                         : null
                select new FileBrowseViewModel.FileEntry
                {
                    Id = file.Id,
                    FullDisplayName = fullDisplayName + "/" + file.DisplayName,
                    DisplayName = file.DisplayName,
                    IsFolder = file is Folder,
                    Size = latestVersion != null ? latestVersion.Blob.Size : 0,
                    TimeStamp = latestVersion != null ? latestVersion.TimeStamp : DateTime.UtcNow,
                    State = file.State,
                    HasInvitation = (file is Folder) ? ((Folder)file).InvitationId != null : false,
                    HasTargetInvitations = (file is Folder) ? ((Folder)file).TargetOfInvitations.Any() : false
                }
                ).ToList();
            model.Parents = new List<Tuple<string, string>>();

            // Construct the parent list for the breadcrumb.

            List<Folder> parentFolders = new List<Folder>();
            Folder currentFolder = folder;

            while (currentFolder != userRootFolder)
            {
                if (currentFolder.TargetOfInvitations.Any())
                {
                    model.SharedFolder = true;

                    // Follow any invitation link backwards.

                    var invitation = _fileManager.GetInvitationForUser(currentFolder, userId);
                    Folder acceptedFolder = null;

                    if (invitation != null)
                        acceptedFolder = invitation.AcceptedFolders.SingleOrDefault();

                    if (acceptedFolder != null)
                    {
                        currentFolder = acceptedFolder;
                        model.SharedWithMe = true;
                    }
                }

                if (currentFolder != userRootFolder)
                    parentFolders.Add(currentFolder);

                currentFolder = currentFolder.ParentFolder;
            };

            parentFolders.Reverse();

            if (parentFolders.Count != 0)
                parentFolders.RemoveAt(parentFolders.Count - 1);

            if (folder != userRootFolder)
                model.Parents.Add(new Tuple<string, string>("Home", ""));

            StringBuilder sb = new StringBuilder();

            foreach (var f in parentFolders)
            {
                sb.Append('/');
                sb.Append(f.DisplayName);

                model.Parents.Add(new Tuple<string, string>(f.DisplayName, sb.ToString()));
            }

            return model;
        }

        private ActionResult DownloadDocument(Document document, DocumentVersion version = null)
        {
            if (version == null)
            {
                // Get latest version
                version = _fileManager.GetLastDocumentVersion(document);
            }
            string blobFileName = _fileManager.GetBlobFileName(version.Blob.Key);
            return File(blobFileName, MimeMapping.GetMimeMapping(document.DisplayName), document.DisplayName);
        }

        public ActionResult Browse()
        {
            string path = (string)RouteData.Values["path"] ?? "";
            string fullDisplayName = null;
            File file = _fileManager.FindFile(path, _fileManager.GetUserRootFolder(User.Identity.GetUserId()), out fullDisplayName);

            if (file == null)
            {
                ModelState.AddModelError("", "The path '" + path + "' is invalid.");
                return View(CreateBrowseModelForFolder(null, null));
            }

            if (file is Document)
            {
                return DownloadDocument((Document)file);
            }
            else
            {
                return View(CreateBrowseModelForFolder((Folder)file, fullDisplayName));
            }
        }

        public ActionResult Versions(string fullName)
        {
            if (fullName == null)
                return RedirectToAction("Browse");

            Folder userRootFolder = _fileManager.GetUserRootFolder(User.Identity.GetUserId());
            string fullDisplayName;
            File file = _fileManager.FindFile(fullName, userRootFolder, out fullDisplayName);

            if (file == null || !(file is Document))
                return RedirectToAction("Browse");

            Document document = (Document)file;
            VersionHistoryViewModel model = new VersionHistoryViewModel();

            model.DisplayName = document.DisplayName;
            model.FullDisplayName = fullDisplayName;
            model.SharedFolder = _fileManager.IsInSharedFolder(document);
            model.Versions = (
                from version in document.DocumentVersions
                orderby version.TimeStamp descending
                select new VersionHistoryViewModel.VersionEntry
                {
                    Size = version.Blob.Size,
                    TimeStamp = version.TimeStamp,
                    VersionId = version.Id,
                    ClientName = version.Client.Name,
                    UserId = version.Client.UserId,
                    UserName = version.Client.User.Name
                }
                ).ToList();

            return View(model);
        }

        public ActionResult DownloadVersion(long? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DocumentVersion version = _fileManager.FindDocumentVersion((long)id);
            if (version == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return DownloadDocument(version.Document, version);
        }

        // POST
        [HttpPost]
        public ActionResult RevertVersion(string fullName, long versionId)
        {
            long userId = User.Identity.GetUserId();
            DocumentVersion version = _fileManager.FindDocumentVersion(versionId);
            if (version == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string dummy;
            string syncFullName;
            File file = _fileManager.FindFile(fullName, _fileManager.GetUserRootFolder(userId), out dummy, out syncFullName);
            if (file == null || !(file is Document))
                return RedirectToAction("Browse");

            var internalClient = _fileManager.GetInternalClient(userId);
            ClientSyncData data = new ClientSyncData();

            data.ClientId = internalClient.Id;
            data.BaseChangelistId = _fileManager.GetLastChangelistId();
            data.Changes.Add(new ClientChange
            {
                FullName = syncFullName,
                Type = ChangeType.Add,
                Hash = version.Blob.Hash,
                Size = version.Blob.Size
            });
            _fileManager.SyncClientChanges(data);

            return RedirectToAction("Versions", new { fullName = fullName });
        }

        private bool NameConflicts(Folder parent, string name, bool creatingDocument, bool newVersion)
        {
            File file = parent.Files.AsQueryable().Where(f => f.Name == name).SingleOrDefault();

            if (file == null || file.State == ObjectState.Deleted)
                return false;

            if (creatingDocument && newVersion && file is Document)
                return false;

            return true;
        }

        private bool EnsureAvailableName(ref string destinationDisplayName, Folder parent, bool creatingDocument, bool newVersion = false)
        {
            const int MaxIterations = 10;

FooBox/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FooBox;
using FooBox.Models;

namespace FooBox.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private UserManager um = new UserManager();

        private bool IsAuthorized()
        {
            return um.IsUserAdmin(User.Identity.GetUserId());
        }

        // GET: User/Index
        public ActionResult Index()
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            return View(um.Context.Users.ToList());
        }

        /*
        // GET: User/UserDetails/5
        public ActionResult UserDetails(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Identities.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        */

        // GET: User/UserCreate
        public ActionResult UserCreate()
        {
            return View();
        }

        // POST: User/UserCreate
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserCreate(AdminNewUserViewModel model)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            User template;
            if (ModelState.IsValid)
            {
                template = new User
                {
                    Name = model.Name,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    QuotaLimit = model.QuotaLimit * (1024 * 1024)
                };
                um.CreateUser(template, model.Password);
                DisplaySuccessMessage("User created");
                return RedirectToAction("Index");
            }

            DisplayErrorMessage();
            return View();
        }

        // GET: User/UserEdit/5
        public ActionResult UserEdit(long? id)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = um.FindUser(id.Value);
            var model = new AdminEditUserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Name = user.Name,
                QuotaLimit = user.QuotaLimit / (1024 * 1024)
            };
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: UserUser/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserEdit(AdminEditUserViewModel model)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            if (ModelState.IsValid)
            {
                User u = um.FindUser(model.Id);
                u.Name = model.Name;
                u.FirstName = model.FirstName;
                u.LastName = model.LastName;
                u.QuotaLimit = model.QuotaLimit * 1024 * 1024;
              
                try
                {
                    um.Context.SaveChanges();
                }
                catch
                {
                    DisplayErrorMessage();
                    return View(model);
                }
                DisplaySuccessMessage("User details updated");
                return RedirectToAction("Index");
            }
            DisplayErrorMessage();
            return View(model);
        }

        // POST: User/UserDelete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserDelete(long? id)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            um.DeleteUser(id.Value);

            DisplaySuccessMessage("User deleted");
            return RedirectToAction("Index");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save change was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                um.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FooBox/Views/Shared/_Layout.cshtml
@using FooBox.Models;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FooBox</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FooBox", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @using (var userManager = new FooBox.Models.UserManager())
                    {
                        if (!string.IsNullOrEmpty(User.Identity.Name))
                        {
                            <li>@Html.ActionLink("Shared Links", "SharedLinks", "File")</li>
                            <li class="dropdown">
                                @Html.Partial("_NotificationsPartial", userManager.FindUser(User.Identity.GetUserId()).Invitations)
                            </li>
                            if (userManager.IsUserAdmin(FooBox.Models.IdentityExtensions.GetUserId(User.Identity)))
                            {
                                <li>@Html.ActionLink("Users", "Index", "User")</li>
                                <li>@Html.ActionLink("Groups", "Index", "Group")</li>
                            }
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6" id="notifications"></div>
            <div class="col-md-3"></div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FooBox</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FooBox/Views/Shared/_NotificationsPartial.cshtml
@model ICollection<FooBox.Invitation>
@{
    int count = Model.Count(item => !item.AcceptedFolders.Any());
    if (count > 0)
    {
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Invitations <span class="badge" id="invitation-count">@count</span></a>
    }
    else
    { 
        @Html.ActionLink("Invitations", "AllInvitations", "Invitation", null, null);
        @*<a href="#" class="dropdown-toggle" data-toggle="dropdown">Invitations <span class="badge" id="invitation-count">@count</span></a>*@
    }
}

@if (count > 0)
{
    <ul class="dropdown-menu" role="menu" id="invitations-dropdown">
        <li><div class="container"><strong>Folder invitations</strong></div></li>
        @foreach (var item in Model)
        {
            if (item.AcceptedFolders.Any()) 
            {
                continue;
            }
            <li id=@string.Format("invite{0}-divider", item.Id) class="divider"></li>
            <li id=@string.Format("invite{0}", item.Id)>
                <div class="container">
                    @item.Target.Owner.Name invited you to access
                    <strong>@item.Target.DisplayName</strong>.
                    <div>
                        @using (Ajax.BeginForm("EditStatus", "Invitation",
                            new AjaxOptions { OnSuccess = string.Format("onChangeInvitationStatusSuccess({0}, data)", item.Id), HttpMethod = "Post" }))
                        {
                            @Html.Hidden("id", item.Id)
                            <button type="submit" class="btn btn-primary btn-xs" name="submit" value="Accept">Accept</button>
                            <button type="submit" class="btn btn-danger btn-xs" name="submit" value="Decline">Decline</button>
                        }
                    </div>
                </div>
            </li>
        }
        <li class="divider"></li>
        <li><div class="container">@Html.ActionLink("View All", "AllInvitations", "Invitation", null, null)</div></li>
    </ul>

}

<script>
    function onChangeInvitationStatusSuccess(id, data) {
        console.log(id);
        var inviteId = '#invite' + String(id);
        var dividerId = inviteId + '-divider';
        $(dividerId).hide();
        $(inviteId).hide();
        var numInvitations = parseInt($('#invitation-count').text());
        numInvitations -= 1;
        $('#invitation-count').text(String(numInvitations));
        if (numInvitations == 0) {
            $('#invitations-dropdown').hide('slide');
        }
        if (data) {
            $('#notifications').append('<div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>A new shared folder <strong>' +
                data.FolderDisplayName +
                '</strong> has been created in your root directory. You may need to <a href="javascript:location.reload()">refresh</a> the page to see it.</div>')
        }
        console.log(data);

    }
</script>