FooBox/Controllers/GroupController.cs
using FooBox.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FooBox.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private UserManager um = new UserManager();

        private bool IsAuthorized()
        {
            return um.IsUserAdmin(User.Identity.GetUserId());
        }

        // GET: Group/Index
        public ActionResult Index()
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            return View(um.Context.Groups);
        }

        // GET: Group/GroupCreate
        public ActionResult GroupCreate()
        {
            var mod = new AdminNewGroupViewModel();
            List<EntitySelectedViewModel> users = new List<EntitySelectedViewModel>();


            foreach (User u in um.Context.Users) 
            {
                if (u.Name.Equals("__DEFAULT__") || u.State == ObjectState.Deleted) { continue; }
                var a = new EntitySelectedViewModel();
                a.Id = u.Id;
                a.IsSelected = false;
                a.Name = u.Name;
                users.Add(a);
            }
            mod.Users = users;
            return View(mod);
        }

        // POST: Group/GroupCreate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GroupCreate(AdminNewGroupViewModel model)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            Group template = null;
            if (ModelState.IsValid)
            {
                template = new Group
                {
                    Name = model.Name,
                    Description = model.Description,
                    IsAdmin = false
                };
                var actual = um.CreateGroup(template);
                actual.Users.Add(um.GetDefaultUser());
                foreach (var item in model.Users) 
                {
                    if (item.IsSelected)
                    {
                        FooBox.User u = um.FindUser(item.Id);
                        if (u != null) actual.Users.Add(u);
                        um.Context.SaveChanges();
                    }
                }           

                DisplaySuccessMessage("User created");
                return RedirectToAction("Index");
            }
         

            DisplayErrorMessage();
            return View(model);
        }




        // GET: Group/GroupEdit/5
        public ActionResult GroupEdit(long? id)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group grp = um.FindGroup(id.Value);

            if (grp == null)
            {
                return HttpNotFound();
            }

            List<EntitySelectedViewModel> users = new List<EntitySelectedViewModel>();

            var mod = new AdminEditGroupViewModel();   
            mod.Id = grp.Id;
            mod.Name = grp.Name;
            mod.Description = grp.Description;
            var userList = um.Context.Users.ToList();
            foreach (User u in userList)
            {
                if (u.Name.Equals("__DEFAULT__") || u.State == ObjectState.Deleted) { continue; }
                var a = new EntitySelectedViewModel();
                a.Id = u.Id;
                a.IsSelected = grp.Users.Contains(u);
                a.Name = u.Name;
                users.Add(a);
            }
            mod.Users = users;
            return View(mod);
        }

        // POST: Group/GroupEdit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GroupEdit(AdminEditGroupViewModel model)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            if (ModelState.IsValid)
            {
                Group g = um.FindGroup(model.Id);
                g.Name = model.Name;
                g.Users.Clear();
                g.Users.Add(um.GetDefaultUser());
                foreach (var item in model.Users)
                {
                    if (item.IsSelected)
                    {
                        FooBox.User u = um.FindUser(item.Id);
                        if (u != null) g.Users.Add(u);
                    }
                } 
                g.Description = model.Description;
                try
                {
                    um.Context.SaveChanges();
                }
                catch
                {
                    DisplayErrorMessage();
                    return View(model);
                }
                DisplaySuccessMessage("Group edited");
                return RedirectToAction("Index");
            }


           
            DisplayErrorMessage();
            return View(model);
        }



        // GET: Group/GroupDelete/5
        public ActionResult GroupDelete(long? id)
        {
            if (!IsAuthorized())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = um.FindGroup(id.Value);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        // POST: Group/GroupDelete/5
        [HttpPost, ActionName("GroupDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult GroupDeleteConfirmed(long id)
        {

            um.DeleteGroup(id);

            DisplaySuccessMessage("Group deleted");
            return RedirectToAction("Index");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save change was unsuccessful.";
        }

    }
}

FooBox/Views/Group/GroupCreate.cshtml
@using Microsoft.AspNet.Identity
@model FooBox.Models.AdminNewGroupViewModel

@{
    ViewBag.Title = "GroupCreate";
}

<h2>Create</h2>


@using (Html.BeginForm("GroupCreate", "Group", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @for (int i = 0; i < Model.Users.Count(); ++i)
                {
                    @Html.HiddenFor(model => model.Users[i].Id)
                    @Html.CheckBoxFor(model => model.Users[i].IsSelected)
                    @Html.DisplayFor(model => model.Users[i].Name)
                    <br>
                }

             </div>
        </div>

        @*<div class="checkbox">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <label>
                    @Html.CheckBoxFor(model => model.IsAdmin, new { @class = "checkbox" })
                    Admin
                </label>
                @Html.ValidationMessageFor(model => model.IsAdmin)
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
   
    
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FooBox/Views/Group/GroupDelete.cshtml
@model FooBox.Group

@{
    ViewBag.Title = "GroupDelete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAdmin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAdmin)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FooBox/Views/Group/GroupEdit.cshtml
@using Microsoft.AspNet.Identity
@model FooBox.Models.AdminEditGroupViewModel

@{
    ViewBag.Title = "GroupEdit";
}

<h2>Edit</h2>

<h4>Group</h4>
<hr />
@using (Html.BeginForm("GroupEdit", "Group", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @for (int i = 0; i < Model.Users.Count(); ++i)
            {
                @Html.HiddenFor(model => model.Users[i].Id)
                @Html.CheckBoxFor(model => model.Users[i].IsSelected)
                @Html.DisplayFor(model => model.Users[i].Name)
                <br>
            }

        </div>
    </div>

    @*<div class="checkbox">
        <div class="col-md-2"></div>
        <div class="col-md-10">
            <label>
                @Html.CheckBoxFor(model => model.IsAdmin, new { @class = "checkbox" })
                Admin
            </label>
            @Html.ValidationMessageFor(model => model.IsAdmin)
        </div>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div id="actionButtons">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" id="deleteButton" class="btn btn-warning btn-default" value="Delete" />
            </div>
        </div>
    </div>
}

<!-- Confirm Delete -->
<div id="confirmDeleteDialog" class="form-group" style="display:none;">
    <div class="col-md-offset-2 col-md-10">
        @using (var form1 = Html.BeginForm("GroupDelete", "Group", new { id = Model.Id }))
        {
            @Html.AntiForgeryToken()

            <button type="submit" class="btn btn-danger">Delete</button>
            <button type="button" id="delCancelButton" class="btn btn-default">Cancel</button>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script>
    $("document").ready(function () {
        $("#deleteButton").click(function () {
            $("#confirmDeleteDialog").show('slide');
            $("#actionButtons").hide();
        });
        $("#delCancelButton").click(function () {
            $("#confirmDeleteDialog").hide();
            $("#actionButtons").show('slide');
        });
    });
    $("")
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FooBox/Views/Group/Index.cshtml
@model IEnumerable<FooBox.Group>

@{
    ViewBag.Title = "Groups";
}

<h2>Groups</h2>



<p>
    @Html.ActionLink("Create New", "GroupCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    if (item.State == ObjectState.Normal) 
    {   
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "GroupEdit", new { id=item.Id })
        </td>
    </tr>
    }
}

</table>